import type { AuditEvent } from "@/lib/types/audit";

export const auditEvents: AuditEvent[] = [
  {
    id: "aud-001",
    type: "SIGNAL_RECEIVED",
    customerId: "cust-marcus-holloway",
    customerName: "Marcus Holloway",
    signalId: "sig-001",
    policyDecision: "Pending evaluation",
    action: "Recorded new automotive lead",
    outcome: "recorded",
    occurredAt: "2026-05-30T13:05:00Z",
  },
  {
    id: "aud-002",
    type: "INTENT_CLASSIFIED",
    customerId: "cust-marcus-holloway",
    customerName: "Marcus Holloway",
    signalId: "sig-001",
    policyDecision: "High intent score 86",
    action: "Classified as purchase intent",
    outcome: "recorded",
    occurredAt: "2026-05-30T13:06:00Z",
  },
  {
    id: "aud-003",
    type: "POLICY_ALLOWED_ACTION",
    customerId: "cust-marcus-holloway",
    customerName: "Marcus Holloway",
    signalId: "sig-001",
    policyDecision: "Consent present (SMS)",
    action: "Approved SMS lead response",
    outcome: "allowed",
    occurredAt: "2026-05-30T13:07:00Z",
  },
  {
    id: "aud-004",
    type: "MESSAGE_DRAFTED",
    customerId: "cust-marcus-holloway",
    customerName: "Marcus Holloway",
    signalId: "sig-001",
    policyDecision: "Consent present (SMS)",
    action: "Drafted SMS lead response",
    outcome: "recorded",
    occurredAt: "2026-05-30T13:08:00Z",
  },
  {
    id: "aud-005",
    type: "CUSTOMER_OPTED_OUT",
    customerId: "cust-ethan-brooks",
    customerName: "Ethan Brooks",
    signalId: "sig-002",
    policyDecision: "Opt-out recorded",
    action: "Stopped all workflows",
    outcome: "recorded",
    occurredAt: "2026-05-30T12:55:00Z",
  },
  {
    id: "aud-006",
    type: "POLICY_BLOCKED_ACTION",
    customerId: "cust-ethan-brooks",
    customerName: "Ethan Brooks",
    signalId: "sig-002",
    policyDecision: "Customer opted out",
    action: "Blocked SMS sales follow-up",
    outcome: "blocked",
    occurredAt: "2026-05-30T12:56:00Z",
  },
  {
    id: "aud-007",
    type: "POLICY_BLOCKED_ACTION",
    customerId: "cust-linda-vasquez",
    customerName: "Linda Vasquez",
    signalId: "sig-003",
    policyDecision: "Medical sensitive message",
    action: "Held reschedule message for review",
    outcome: "review",
    occurredAt: "2026-05-30T08:25:00Z",
  },
  {
    id: "aud-008",
    type: "HUMAN_TASK_CREATED",
    customerId: "cust-linda-vasquez",
    customerName: "Linda Vasquez",
    signalId: "sig-003",
    policyDecision: "Human review required",
    action: "Created scheduling review task",
    outcome: "review",
    occurredAt: "2026-05-30T08:30:00Z",
  },
  {
    id: "aud-009",
    type: "VOICE_CALL_QUEUED",
    customerId: "cust-denise-carter",
    customerName: "Denise Carter",
    signalId: "sig-007",
    policyDecision: "Consent present (voice)",
    action: "Queued simulated maintenance recovery call",
    outcome: "allowed",
    occurredAt: "2026-05-30T12:45:00Z",
  },
  {
    id: "aud-010",
    type: "HUMAN_TASK_CREATED",
    customerId: "cust-jordan-mills",
    customerName: "Jordan Mills",
    signalId: "sig-008",
    policyDecision: "Human review required",
    action: "Created intake qualification task",
    outcome: "review",
    occurredAt: "2026-05-30T10:05:00Z",
  },
];

export function getAuditEvent(id: string): AuditEvent | undefined {
  return auditEvents.find((event) => event.id === id);
}
