import type { Customer } from "@/lib/types/customer";

export const customers: Customer[] = [
  {
    id: "cust-marcus-holloway",
    name: "Marcus Holloway",
    vertical: "automotive",
    channels: [
      { channel: "sms", value: "+1 (414) 555-0142", consent: "granted" },
      { channel: "email", value: "m.holloway@example.com", consent: "granted" },
      { channel: "voice", value: "+1 (414) 555-0142", consent: "unknown" },
    ],
    preferredChannel: "sms",
    optedOut: false,
    recentSignals: ["New Silverado 1500 inquiry", "Trade-in valuation viewed"],
    activeOpportunity: "Silverado 1500 LT purchase",
    lastAction: "Drafted SMS lead response",
    lastActionAt: "2026-05-30T13:10:00Z",
    riskFlags: [],
  },
  {
    id: "cust-denise-carter",
    name: "Denise Carter",
    vertical: "automotive",
    channels: [
      { channel: "sms", value: "+1 (262) 555-0188", consent: "granted" },
      { channel: "email", value: "denise.carter@example.com", consent: "denied" },
      { channel: "voice", value: "+1 (262) 555-0188", consent: "granted" },
    ],
    preferredChannel: "voice",
    optedOut: false,
    recentSignals: ["Service overdue by 2 months", "Declined last service quote"],
    activeOpportunity: "30k mile maintenance package",
    lastAction: "Queued maintenance recovery call",
    lastActionAt: "2026-05-30T12:45:00Z",
    riskFlags: [{ label: "Lapsed service customer", severity: "warning" }],
  },
  {
    id: "cust-priya-nair",
    name: "Priya Nair",
    vertical: "dental",
    channels: [
      { channel: "sms", value: "+1 (847) 555-0110", consent: "granted" },
      { channel: "email", value: "priya.nair@example.com", consent: "granted" },
      { channel: "voice", value: "+1 (847) 555-0110", consent: "unknown" },
    ],
    preferredChannel: "email",
    optedOut: false,
    recentSignals: ["Cleaning overdue by 7 months", "Unscheduled treatment plan"],
    activeOpportunity: "Recall cleaning and exam",
    lastAction: "Drafted recall reminder email",
    lastActionAt: "2026-05-30T11:20:00Z",
    riskFlags: [{ label: "Elevated compliance handling", severity: "info" }],
  },
  {
    id: "cust-avery-thompson",
    name: "Avery Thompson",
    vertical: "home-services",
    channels: [
      { channel: "sms", value: "+1 (503) 555-0173", consent: "granted" },
      { channel: "email", value: "avery.thompson@example.com", consent: "granted" },
      { channel: "voice", value: "+1 (503) 555-0173", consent: "granted" },
    ],
    preferredChannel: "sms",
    optedOut: false,
    recentSignals: ["HVAC estimate request", "Viewed financing options"],
    activeOpportunity: "Central AC replacement estimate",
    lastAction: "Queued estimate scheduling SMS",
    lastActionAt: "2026-05-30T13:25:00Z",
    riskFlags: [],
  },
  {
    id: "cust-jordan-mills",
    name: "Jordan Mills",
    vertical: "legal-intake",
    channels: [
      { channel: "sms", value: "+1 (312) 555-0166", consent: "unknown" },
      { channel: "email", value: "jordan.mills@example.com", consent: "granted" },
      { channel: "voice", value: "+1 (312) 555-0166", consent: "unknown" },
    ],
    preferredChannel: "email",
    optedOut: false,
    recentSignals: ["Consultation request submitted", "Intake form partially completed"],
    activeOpportunity: "Initial consultation booking",
    lastAction: "Created human intake task",
    lastActionAt: "2026-05-30T10:05:00Z",
    riskFlags: [{ label: "Advice boundary review required", severity: "warning" }],
  },
  {
    id: "cust-sofia-ramirez",
    name: "Sofia Ramirez",
    vertical: "insurance",
    channels: [
      { channel: "sms", value: "+1 (305) 555-0129", consent: "granted" },
      { channel: "email", value: "sofia.ramirez@example.com", consent: "granted" },
      { channel: "voice", value: "+1 (305) 555-0129", consent: "denied" },
    ],
    preferredChannel: "sms",
    optedOut: false,
    recentSignals: ["Missed agent call", "Auto policy renewal due in 14 days"],
    activeOpportunity: "Auto policy renewal review",
    lastAction: "Drafted renewal reminder SMS",
    lastActionAt: "2026-05-29T16:40:00Z",
    riskFlags: [],
  },
  {
    id: "cust-ethan-brooks",
    name: "Ethan Brooks",
    vertical: "automotive",
    channels: [
      { channel: "sms", value: "+1 (414) 555-0199", consent: "revoked" },
      { channel: "email", value: "ethan.brooks@example.com", consent: "denied" },
      { channel: "voice", value: "+1 (414) 555-0199", consent: "revoked" },
    ],
    preferredChannel: "email",
    optedOut: true,
    recentSignals: ["Missed sales call", "Replied STOP to SMS"],
    activeOpportunity: null,
    lastAction: "Recorded opt-out and stopped workflow",
    lastActionAt: "2026-05-29T09:15:00Z",
    riskFlags: [{ label: "Opted out of all outreach", severity: "critical" }],
  },
  {
    id: "cust-linda-vasquez",
    name: "Linda Vasquez",
    vertical: "medical",
    channels: [
      { channel: "sms", value: "+1 (210) 555-0157", consent: "granted" },
      { channel: "email", value: "linda.vasquez@example.com", consent: "unknown" },
      { channel: "voice", value: "+1 (210) 555-0157", consent: "granted" },
    ],
    preferredChannel: "voice",
    optedOut: false,
    recentSignals: ["Appointment cancellation", "Annual visit due"],
    activeOpportunity: "Reschedule annual visit",
    lastAction: "Routed to human review for sensitive content",
    lastActionAt: "2026-05-30T08:30:00Z",
    riskFlags: [{ label: "Protected health information", severity: "critical" }],
  },
];

export function getCustomer(id: string): Customer | undefined {
  return customers.find((customer) => customer.id === id);
}
