import type { Opportunity } from "@/lib/types/opportunity";

export const opportunities: Opportunity[] = [
  {
    id: "opp-001",
    title: "Silverado 1500 LT purchase",
    customerId: "cust-marcus-holloway",
    customerName: "Marcus Holloway",
    vertical: "automotive",
    stage: "engaged",
    intentScore: 86,
    estimatedValue: 52000,
    owner: "Sales: River North",
    updatedAt: "2026-05-30T13:10:00Z",
  },
  {
    id: "opp-002",
    title: "Central AC replacement estimate",
    customerId: "cust-avery-thompson",
    customerName: "Avery Thompson",
    vertical: "home-services",
    stage: "new",
    intentScore: 74,
    estimatedValue: 9800,
    owner: "Dispatch queue",
    updatedAt: "2026-05-30T13:25:00Z",
  },
  {
    id: "opp-003",
    title: "30k mile maintenance package",
    customerId: "cust-denise-carter",
    customerName: "Denise Carter",
    vertical: "automotive",
    stage: "contact-attempted",
    intentScore: 58,
    estimatedValue: 1200,
    owner: "Service BDC",
    updatedAt: "2026-05-30T12:45:00Z",
  },
  {
    id: "opp-004",
    title: "Recall cleaning and exam",
    customerId: "cust-priya-nair",
    customerName: "Priya Nair",
    vertical: "dental",
    stage: "appointment-set",
    intentScore: 69,
    estimatedValue: 480,
    owner: "Front desk",
    updatedAt: "2026-05-30T11:20:00Z",
  },
  {
    id: "opp-005",
    title: "Initial consultation booking",
    customerId: "cust-jordan-mills",
    customerName: "Jordan Mills",
    vertical: "legal-intake",
    stage: "needs-human-review",
    intentScore: 71,
    estimatedValue: 3500,
    owner: "Intake specialist",
    updatedAt: "2026-05-30T10:05:00Z",
  },
  {
    id: "opp-006",
    title: "Auto policy renewal review",
    customerId: "cust-sofia-ramirez",
    customerName: "Sofia Ramirez",
    vertical: "insurance",
    stage: "engaged",
    intentScore: 63,
    estimatedValue: 1400,
    owner: "Agency line",
    updatedAt: "2026-05-29T16:40:00Z",
  },
  {
    id: "opp-007",
    title: "Reschedule annual visit",
    customerId: "cust-linda-vasquez",
    customerName: "Linda Vasquez",
    vertical: "medical",
    stage: "needs-human-review",
    intentScore: 55,
    estimatedValue: 320,
    owner: "Scheduling team",
    updatedAt: "2026-05-30T08:30:00Z",
  },
  {
    id: "opp-008",
    title: "Used sedan inquiry",
    customerId: "cust-ethan-brooks",
    customerName: "Ethan Brooks",
    vertical: "automotive",
    stage: "lost",
    intentScore: 12,
    estimatedValue: 0,
    owner: "Sales: River North",
    updatedAt: "2026-05-29T09:15:00Z",
  },
  {
    id: "opp-009",
    title: "Trade-in reactivation",
    customerId: "cust-denise-carter",
    customerName: "Denise Carter",
    vertical: "automotive",
    stage: "dormant",
    intentScore: 31,
    estimatedValue: 28000,
    owner: "Sales: River North",
    updatedAt: "2026-05-22T14:00:00Z",
  },
  {
    id: "opp-010",
    title: "Spring tune-up offer",
    customerId: "cust-avery-thompson",
    customerName: "Avery Thompson",
    vertical: "home-services",
    stage: "reactivated",
    intentScore: 48,
    estimatedValue: 240,
    owner: "Dispatch queue",
    updatedAt: "2026-05-28T15:30:00Z",
  },
  {
    id: "opp-011",
    title: "Treatment plan acceptance",
    customerId: "cust-priya-nair",
    customerName: "Priya Nair",
    vertical: "dental",
    stage: "won",
    intentScore: 92,
    estimatedValue: 2100,
    owner: "Treatment coordinator",
    updatedAt: "2026-05-27T13:45:00Z",
  },
];

export function getOpportunity(id: string): Opportunity | undefined {
  return opportunities.find((opportunity) => opportunity.id === id);
}
