import type { Signal } from "@/lib/types/signal";

export const signals: Signal[] = [
  {
    id: "sig-001",
    type: "new-lead",
    label: "New automotive lead",
    customerId: "cust-marcus-holloway",
    customerName: "Marcus Holloway",
    vertical: "automotive",
    source: "web-form",
    priority: "high",
    recommendedAction: "Send instant lead response and offer a test drive",
    recommendedChannel: "sms",
    consentStatus: "granted",
    detail: "Requested pricing on a new Silverado 1500 LT with a trade-in.",
    receivedAt: "2026-05-30T13:05:00Z",
  },
  {
    id: "sig-002",
    type: "missed-call",
    label: "Missed sales call",
    customerId: "cust-ethan-brooks",
    customerName: "Ethan Brooks",
    vertical: "automotive",
    source: "phone",
    priority: "medium",
    recommendedAction: "No outreach. Customer opted out.",
    recommendedChannel: "human",
    consentStatus: "revoked",
    detail: "Inbound call missed after hours. Customer previously replied STOP.",
    receivedAt: "2026-05-30T12:55:00Z",
  },
  {
    id: "sig-003",
    type: "appointment-cancellation",
    label: "Appointment cancellation",
    customerId: "cust-linda-vasquez",
    customerName: "Linda Vasquez",
    vertical: "medical",
    source: "scheduler",
    priority: "high",
    recommendedAction: "Route to human review before any reschedule message",
    recommendedChannel: "human",
    consentStatus: "granted",
    detail: "Cancelled annual visit. Content is medical sensitive and needs review.",
    receivedAt: "2026-05-30T08:20:00Z",
  },
  {
    id: "sig-004",
    type: "email-engagement",
    label: "Email engagement",
    customerId: "cust-priya-nair",
    customerName: "Priya Nair",
    vertical: "dental",
    source: "email",
    priority: "medium",
    recommendedAction: "Follow up on recall cleaning with a scheduling link",
    recommendedChannel: "email",
    consentStatus: "granted",
    detail: "Opened recall reminder twice and clicked the scheduling link.",
    receivedAt: "2026-05-30T11:10:00Z",
  },
  {
    id: "sig-005",
    type: "recall-opportunity",
    label: "Dental recall opportunity",
    customerId: "cust-priya-nair",
    customerName: "Priya Nair",
    vertical: "dental",
    source: "third-party",
    priority: "medium",
    recommendedAction: "Send recall reminder and offer the next open slot",
    recommendedChannel: "email",
    consentStatus: "granted",
    detail: "Cleaning overdue by 7 months with an unscheduled treatment plan.",
    receivedAt: "2026-05-30T10:50:00Z",
  },
  {
    id: "sig-006",
    type: "estimate-request",
    label: "Home services estimate request",
    customerId: "cust-avery-thompson",
    customerName: "Avery Thompson",
    vertical: "home-services",
    source: "web-form",
    priority: "critical",
    recommendedAction: "Schedule an estimate visit within the same day",
    recommendedChannel: "sms",
    consentStatus: "granted",
    detail: "Requested a central AC replacement estimate before summer demand.",
    receivedAt: "2026-05-30T13:20:00Z",
  },
  {
    id: "sig-007",
    type: "service-due",
    label: "Service due reminder",
    customerId: "cust-denise-carter",
    customerName: "Denise Carter",
    vertical: "automotive",
    source: "scheduler",
    priority: "medium",
    recommendedAction: "Offer a maintenance recovery call with a service coupon",
    recommendedChannel: "voice",
    consentStatus: "granted",
    detail: "Maintenance overdue by two months after a declined prior quote.",
    receivedAt: "2026-05-30T12:40:00Z",
  },
  {
    id: "sig-008",
    type: "consultation-request",
    label: "Legal intake consultation request",
    customerId: "cust-jordan-mills",
    customerName: "Jordan Mills",
    vertical: "legal-intake",
    source: "web-form",
    priority: "high",
    recommendedAction: "Qualify the intake and route to an attorney handoff",
    recommendedChannel: "human",
    consentStatus: "unknown",
    detail: "Requested a consultation. SMS consent is not yet captured.",
    receivedAt: "2026-05-30T10:00:00Z",
  },
];

export function getSignal(id: string): Signal | undefined {
  return signals.find((signal) => signal.id === id);
}
