import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, PhoneCall } from "lucide-react";
import { SectionHeading } from "@/components/section-heading";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { RecommendationCard } from "@/components/ai/recommendation-card";
import { getReviewQueue } from "@/lib/services/review-service";
import { getVoiceCommandCenter } from "@/lib/services/voice-command-center-service";
import { reviewStateStyles } from "@/lib/config/ai-status";
import {
  voiceComplianceStyles,
  voicePriorityStyles,
} from "@/lib/config/voice-status";
import {
  VOICE_BLOCKED_REASON_LABELS,
  VOICE_PURPOSE_LABELS,
} from "@/lib/types/voice";
import type { VoiceBlockedReason } from "@/lib/types/voice";
import { guardPage } from "@/lib/auth/guard-page";
import { hasPermission } from "@/lib/auth/authorization";
import { VoiceReviewButtons } from "@/components/voice/voice-review-buttons";

export const metadata: Metadata = { title: "Review Queue" };
export const dynamic = "force-dynamic";

export default async function ReviewQueuePage() {
  const { context, denied } = await guardPage("VIEW_AI_RECOMMENDATIONS");
  if (denied) return denied;

  const [{ groups, pendingCount }, voice] = await Promise.all([
    getReviewQueue(context),
    getVoiceCommandCenter(context),
  ]);
  const voiceNeedingReview = voice.needingReview;
  const canReviewVoice = hasPermission(context, "REVIEW_AI_RECOMMENDATIONS");

  return (
    <>
      <SectionHeading
        title="Human review queue"
        description="AI recommendations and simulated voice plans do not become actions automatically. Each one is reviewed by a human. Recommendations are grouped by review state. Voice plans needing review are surfaced below."
        actions={
          <Badge variant="warning">
            {pendingCount + voiceNeedingReview.length} awaiting review
          </Badge>
        }
      />

      {voiceNeedingReview.length > 0 ? (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between gap-2">
              <span className="flex items-center gap-2">
                <PhoneCall className="h-4 w-4 text-warning" />
                Simulated voice plans needing review
              </span>
              <Badge variant="warning">{voiceNeedingReview.length}</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <p className="text-xs text-muted-foreground">
              These voice plans were generated by the deterministic plan engine
              and held back by the voice compliance engine. They will not be
              simulated as completed until a human approves them. Voice plans
              reuse the same governance model as AI recommendations.
            </p>
            <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
              {voiceNeedingReview.slice(0, 6).map((plan) => (
                <div
                  key={plan.id}
                  className="rounded-md border border-border bg-secondary/30 p-3"
                >
                  <div className="flex items-center justify-between gap-2">
                    <span className="truncate text-sm font-medium">
                      {plan.customerName}
                    </span>
                    <Badge variant={voicePriorityStyles[plan.priority].variant}>
                      {voicePriorityStyles[plan.priority].label}
                    </Badge>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    {VOICE_PURPOSE_LABELS[plan.purpose]} (
                    {plan.vertical.replace("-", " ")})
                  </p>
                  <div className="mt-1 flex items-center gap-2">
                    <Badge
                      variant={voiceComplianceStyles[plan.complianceStatus].variant}
                    >
                      {voiceComplianceStyles[plan.complianceStatus].label}
                    </Badge>
                    <span className="truncate text-xs text-muted-foreground">
                      {plan.blockedReason
                        ? VOICE_BLOCKED_REASON_LABELS[
                            plan.blockedReason as VoiceBlockedReason
                          ]
                        : "Awaiting human approval"}
                    </span>
                  </div>
                  <div className="mt-2">
                    <VoiceReviewButtons
                      voicePlanId={plan.id}
                      canReview={canReviewVoice}
                    />
                  </div>
                </div>
              ))}
            </div>
            <Link
              href="/voice-command-center"
              className="inline-flex items-center gap-1 text-xs text-primary hover:underline"
            >
              Open voice command center
              <ArrowRight className="h-3.5 w-3.5" />
            </Link>
          </CardContent>
        </Card>
      ) : null}

      {groups.length > 0 ? (
        <div className="space-y-8">
          {groups.map((group) => {
            const style = reviewStateStyles[group.state];
            return (
              <section key={group.state} className="space-y-3">
                <div className="flex items-center gap-2">
                  <h2 className="text-sm font-semibold">{style.label}</h2>
                  <Badge variant={style.variant}>{group.items.length}</Badge>
                </div>
                <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                  {group.items.map((recommendation) => (
                    <RecommendationCard
                      key={recommendation.id}
                      recommendation={recommendation}
                      href={`/ai-center/${recommendation.id}`}
                    />
                  ))}
                </div>
              </section>
            );
          })}
        </div>
      ) : (
        <p className="rounded-md border border-dashed border-border p-8 text-center text-sm text-muted-foreground">
          No recommendations to review. Run the seed script to generate demo
          data.
        </p>
      )}
    </>
  );
}
