/*
 * Safety scan. Fails the build if the codebase contains banned content:
 * attribution footers, Claude URLs, real provider secret env names, network
 * calls, or em dashes; or if package.json declares a banned provider SDK.
 *
 * Documentation may reference future provider names. The scan targets code and
 * secrets, and treats the em dash and attribution strings as banned everywhere.
 */
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, extname } from "node:path";

const ROOT = process.cwd();

// Directories never scanned.
const IGNORE_DIRS = new Set([
  "node_modules",
  ".next",
  ".git",
  "coverage",
  "dist",
]);

// Banned substrings in code and docs. The em dash is the unicode character
// U+2014, referenced here by escape so this file contains no literal em dash.
const EM_DASH = "—";
const BANNED_EVERYWHERE: { needle: string; label: string }[] = [
  { needle: "Generated by Claude", label: "attribution footer" },
  { needle: "Built by Claude", label: "attribution footer" },
  { needle: "Created with Claude", label: "attribution footer" },
  { needle: "claude.ai", label: "Claude URL" },
  { needle: EM_DASH, label: "em dash" },
];

// Banned in code files only (not docs): real secret env names and network calls.
const BANNED_IN_CODE: { needle: string; label: string }[] = [
  { needle: "OPENAI_API_KEY", label: "secret env name" },
  { needle: "ANTHROPIC_API_KEY", label: "secret env name" },
  { needle: "GEMINI_API_KEY", label: "secret env name" },
  { needle: "ELEVENLABS_API_KEY", label: "secret env name" },
  { needle: "TWILIO_AUTH_TOKEN", label: "secret env name" },
  { needle: "SENDGRID_API_KEY", label: "secret env name" },
  { needle: "fetch(", label: "network call" },
  { needle: "axios", label: "network dependency" },
];

// Secret env names are allowed when suffixed as a documented placeholder.
function isPlaceholder(line: string, needle: string): boolean {
  return line.includes(`${needle}_PLACEHOLDER`);
}

// Banned provider SDK package names in package.json dependencies.
const BANNED_SDKS = [
  "openai",
  "@anthropic-ai/sdk",
  "@google/generative-ai",
  "elevenlabs",
  "twilio",
  "@sendgrid/mail",
  "axios",
];

const CODE_EXT = new Set([".ts", ".tsx", ".js", ".mjs", ".cjs"]);
const TEXT_EXT = new Set([".ts", ".tsx", ".js", ".mjs", ".cjs", ".md", ".json", ".prisma"]);

type Finding = { file: string; line: number; label: string; text: string };
const findings: Finding[] = [];

// The scan scripts and the quality checklist legitimately name the banned
// needles as detection patterns or as documented commands, so they are
// excluded from the content scan.
const EXCLUDED = new Set([
  join("scripts", "scan-safety.ts"),
  join("scripts", "check-architecture-boundaries.ts"),
  join("docs", "REPO_QUALITY_CHECKLIST.md"),
]);

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = full.slice(ROOT.length + 1);
    if (IGNORE_DIRS.has(entry)) continue;
    const st = statSync(full);
    if (st.isDirectory()) {
      out.push(...walk(full));
    } else if (TEXT_EXT.has(extname(entry))) {
      if (EXCLUDED.has(rel)) continue;
      out.push(full);
    }
  }
  return out;
}

for (const file of walk(ROOT)) {
  const rel = file.slice(ROOT.length + 1);
  const isCode = CODE_EXT.has(extname(file));
  const lines = readFileSync(file, "utf8").split("\n");
  lines.forEach((line, index) => {
    for (const { needle, label } of BANNED_EVERYWHERE) {
      if (line.includes(needle)) {
        findings.push({ file: rel, line: index + 1, label, text: line.trim().slice(0, 100) });
      }
    }
    if (isCode) {
      for (const { needle, label } of BANNED_IN_CODE) {
        if (line.includes(needle) && !isPlaceholder(line, needle)) {
          findings.push({ file: rel, line: index + 1, label, text: line.trim().slice(0, 100) });
        }
      }
    }
  });
}

// Scan package.json for banned SDKs.
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
};
const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
for (const sdk of BANNED_SDKS) {
  if (deps[sdk]) {
    findings.push({ file: "package.json", line: 0, label: "banned provider SDK", text: sdk });
  }
}

if (findings.length > 0) {
  console.error(`Safety scan failed with ${findings.length} finding(s):`);
  for (const f of findings) {
    console.error(`  ${f.file}:${f.line} [${f.label}] ${f.text}`);
  }
  process.exit(1);
}

console.log("Safety scan passed. No banned content found.");
